# Site settings
title: Learn French Words
email: your-email@example.com
description: >-
  A website to help you learn French words through interactive flashcards and other tools. 
  Improve your vocabulary and language skills with ease.
baseurl: "" # Keep this as an empty string since the site is at the root level.
url: "http://learnfrenchwords.com" # The base URL for your site.

# Social media usernames (optional)
twitter_username: your_twitter_username
github_username:  your_github_username

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing (optional)
# You can uncomment and add any files or directories you don't want Jekyll to process.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
