export const animalFlashcards = [
    {emoji: '🐒', french: 'le singe', plural: 'les singes', english: 'Monkey'},
    {emoji: '🦍', french: 'le gorille', plural: 'les gorilles', english: 'Gorilla'},
    {emoji: '🦧', french: 'l’orang-outan', plural: 'les orangs-outans', english: 'Orangutan'},
    {emoji: '🐕', french: 'le chien', plural: 'les chiens', english: 'Dog'},
    {emoji: '🦮', french: 'le chien guide', plural: 'les chiens guides', english: 'Guide Dog'},
    {emoji: '🐕‍🦺', french: 'le chien de service', plural: 'les chiens de service', english: 'Service Dog'},
    {emoji: '🐩', french: 'le caniche', plural: 'les caniches', english: 'Poodle'},
    {emoji: '🐺', french: 'le loup', plural: 'les loups', english: 'Wolf'},
    {emoji: '🦊', french: 'le renard', plural: 'les renards', english: 'Fox'},
    {emoji: '🦝', french: 'le raton laveur', plural: 'les ratons laveurs', english: 'Raccoon'},
    {emoji: '🐈', french: 'le chat', plural: 'les chats', english: 'Cat'},
    {emoji: '🦁', french: 'le lion', plural: 'les lions', english: 'Lion'},
    {emoji: '🐅', french: 'le tigre', plural: 'les tigres', english: 'Tiger'},
    {emoji: '🐆', french: 'le léopard', plural: 'les léopards', english: 'Leopard'},
    {emoji: '🐎', french: 'le cheval', plural: 'les chevaux', english: 'Horse'},
    {emoji: '🦄', french: 'la licorne', plural: 'les licornes', english: 'Unicorn'},
    {emoji: '🦓', french: 'le zèbre', plural: 'les zèbres', english: 'Zebra'},
    {emoji: '🦌', french: 'le cerf', plural: 'les cerfs', english: 'Deer'},
    {emoji: '🐂', french: 'le taureau', plural: 'les taureaux', english: 'Ox'},
    {emoji: '🐃', french: 'le buffle', plural: 'les buffles', english: 'Water Buffalo'},
    {emoji: '🐄', french: 'la vache', plural: 'les vaches', english: 'Cow'},
    {emoji: '🐖', french: 'le porc', plural: 'les porcs', english: 'Pig'},
    {emoji: '🐗', french: 'le sanglier', plural: 'les sangliers', english: 'Boar'},
    {emoji: '🐽', french: 'le museau de porc', plural: 'les museaux de porc', english: 'Pig Nose'},
    {emoji: '🐏', french: 'le bélier', plural: 'les béliers', english: 'Ram'},
    {emoji: '🐑', french: 'la brebis', plural: 'les brebis', english: 'Ewe'},
    {emoji: '🐐', french: 'la chèvre', plural: 'les chèvres', english: 'Goat'},
    {emoji: '🐪', french: 'le chameau', plural: 'les chameaux', english: 'Camel'},
    {emoji: '🐫', french: 'le dromadaire', plural: 'les dromadaires', english: 'Two-Hump Camel'},
    {emoji: '🦙', french: 'le lama', plural: 'les lamas', english: 'Llama'},
    {emoji: '🦒', french: 'la girafe', plural: 'les girafes', english: 'Giraffe'},
    {emoji: '🐘', french: 'l’éléphant', plural: 'les éléphants', english: 'Elephant'},
    {emoji: '🦏', french: 'le rhinocéros', plural: 'les rhinocéros', english: 'Rhinoceros'},
    {emoji: '🦛', french: 'l’hippopotame', plural: 'les hippopotames', english: 'Hippopotamus'},
    {emoji: '🐁', french: 'la souris', plural: 'les souris', english: 'Mouse'},
    {emoji: '🐀', french: 'le rat', plural: 'les rats', english: 'Rat'},
    {emoji: '🐹', french: 'le hamster', plural: 'les hamsters', english: 'Hamster'},
    {emoji: '🐇', french: 'le lapin', plural: 'les lapins', english: 'Rabbit'},
    {emoji: '🐿️', french: 'le tamia', plural: 'les tamias', english: 'Chipmunk'},
    {emoji: '🦔', french: 'le hérisson', plural: 'les hérissons', english: 'Hedgehog'},
    {emoji: '🦇', french: 'la chauve-souris', plural: 'les chauves-souris', english: 'Bat'},
    {emoji: '🐻', french: 'l’ours', plural: 'les ours', english: 'Bear'},
    {emoji: '🐨', french: 'le koala', plural: 'les koalas', english: 'Koala'},
    {emoji: '🐼', french: 'le panda', plural: 'les pandas', english: 'Panda'},
    {emoji: '🦥', french: 'le paresseux', plural: 'les paresseux', english: 'Sloth'},
    {emoji: '🦦', french: 'la loutre', plural: 'les loutres', english: 'Otter'},
    {emoji: '🦨', french: 'le putois', plural: 'les putois', english: 'Skunk'},
    {emoji: '🦘', french: 'le kangourou', plural: 'les kangourous', english: 'Kangaroo'},
    {emoji: '🦡', french: 'le blaireau', plural: 'les blaireaux', english: 'Badger'},
    {emoji: '🐾', french: 'les empreintes de pattes', plural: 'les empreintes de pattes', english: 'Paw Prints'},
    {emoji: '🦃', french: 'la dinde', plural: 'les dindes', english: 'Turkey'},
    {emoji: '🐔', french: 'le poulet', plural: 'les poulets', english: 'Chicken'},
    {emoji: '🐓', french: 'le coq', plural: 'les coqs', english: 'Rooster'},
    {emoji: '🐣', french: 'le poussin éclos', plural: 'les poussins éclos', english: 'Hatching Chick'},
    {emoji: '🐤', french: 'le poussin', plural: 'les poussins', english: 'Baby Chick'},
    {emoji: '🐦', french: 'l’oiseau', plural: 'les oiseaux', english: 'Bird'},
    {emoji: '🐧', french: 'le pingouin', plural: 'les pingouins', english: 'Penguin'},
    {emoji: '🕊️', french: 'la colombe', plural: 'les colombes', english: 'Dove'},
    {emoji: '🦅', french: 'l’aigle', plural: 'les aigles', english: 'Eagle'},
    {emoji: '🦆', french: 'le canard', plural: 'les canards', english: 'Duck'},
    {emoji: '🦢', french: 'le cygne', plural: 'les cygnes', english: 'Swan'},
    {emoji: '🦉', french: 'le hibou', plural: 'les hiboux', english: 'Owl'},
    {emoji: '🦩', french: 'le flamant', plural: 'les flamants', english: 'Flamingo'},
    {emoji: '🦚', french: 'le paon', plural: 'les paons', english: 'Peacock'},
    {emoji: '🦜', french: 'le perroquet', plural: 'les perroquets', english: 'Parrot'},
    {emoji: '🐸', french: 'la grenouille', plural: 'les grenouilles', english: 'Frog'},
    {emoji: '🐊', french: 'le crocodile', plural: 'les crocodiles', english: 'Crocodile'},
    {emoji: '🐢', french: 'la tortue', plural: 'les tortues', english: 'Turtle'},
    {emoji: '🦎', french: 'le lézard', plural: 'les lézards', english: 'Lizard'},
    {emoji: '🐍', french: 'le serpent', plural: 'les serpents', english: 'Snake'},
    {emoji: '🐉', french: 'le dragon', plural: 'les dragons', english: 'Dragon'},
    {emoji: '🦕', french: 'le saurien', plural: 'les sauriens', english: 'Sauropod'},
    {emoji: '🦖', french: 'le T-Rex', plural: 'les T-Rex', english: 'T-Rex'},
    {emoji: '🐳', french: 'la baleine jaillissante', plural: 'les baleines jaillissantes', english: 'Spouting Whale'},
    {emoji: '🐋', french: 'la baleine', plural: 'les baleines', english: 'Whale'},
    {emoji: '🐬', french: 'le dauphin', plural: 'les dauphins', english: 'Dolphin'},
    {emoji: '🐟', french: 'le poisson', plural: 'les poissons', english: 'Fish'},
    {emoji: '🐠', french: 'le poisson tropical', plural: 'les poissons tropicaux', english: 'Tropical Fish'},
    {emoji: '🐡', french: 'le poisson-globe', plural: 'les poissons-globes', english: 'Blowfish'},
    {emoji: '🦈', french: 'le requin', plural: 'les requins', english: 'Shark'},
    {emoji: '🐙', french: 'le poulpe', plural: 'les poulpes', english: 'Octopus'},
    {emoji: '🐚', french: 'la coquille en spirale', plural: 'les coquilles en spirale', english: 'Spiral Shell'},
    {emoji: '🐌', french: 'l’escargot', plural: 'les escargots', english: 'Snail'},
    {emoji: '🦋', french: 'le papillon', plural: 'les papillons', english: 'Butterfly'},
    {emoji: '🐛', french: 'le ver', plural: 'les vers', english: 'Bug'},
    {emoji: '🐜', french: 'la fourmi', plural: 'les fourmis', english: 'Ant'},
    {emoji: '🐝', french: 'l’abeille', plural: 'les abeilles', english: 'Honeybee'},
    {emoji: '🐞', french: 'la coccinelle', plural: 'les coccinelles', english: 'Lady Beetle'},
    {emoji: '🦗', french: 'le grillon', plural: 'les grillons', english: 'Cricket'},
    {emoji: '🕷️', french: 'l’araignée', plural: 'les araignées', english: 'Spider'},
    {emoji: '🕸️', french: 'la toile d’araignée', plural: 'les toiles d’araignée', english: 'Spider Web'},
    {emoji: '🦂', french: 'le scorpion', plural: 'les scorpions', english: 'Scorpion'},
    {emoji: '🦟', french: 'le moustique', plural: 'les moustiques', english: 'Mosquito'},
   
];