export const foodFlashcards = [
    {emoji: '🍏', french: 'la pomme', plural: 'les pommes', english: 'apple'},
    {emoji: '🍎', french: 'la pomme rouge', plural: 'les pommes rouges', english: 'red apple'},
    {emoji: '🍐', french: 'la poire', plural: 'les poires', english: 'pear'},
    {emoji: '🍊', french: 'l\'orange', plural: 'les oranges', english: 'orange'},
    {emoji: '🍋', french: 'le citron', plural: 'les citrons', english: 'lemon'},
    {emoji: '🍌', french: 'la banane', plural: 'les bananes', english: 'banana'},
    {emoji: '🍉', french: 'la pastèque', plural: 'les pastèques', english: 'watermelon'},
    {emoji: '🍇', french: 'le raisin', plural: 'les raisins', english: 'grape'},
    {emoji: '🍓', french: 'la fraise', plural: 'les fraises', english: 'strawberry'},
    {emoji: '🍈', french: 'le melon', plural: 'les melons', english: 'melon'},
    {emoji: '🍒', french: 'la cerise', plural: 'les cerises', english: 'cherry'},
    {emoji: '🍑', french: 'la pêche', plural: 'les pêches', english: 'peach'},
    {emoji: '🥭', french: 'la mangue', plural: 'les mangues', english: 'mango'},
    {emoji: '🍍', french: 'l\'ananas', plural: 'les ananas', english: 'pineapple'},
    {emoji: '🥥', french: 'la noix de coco', plural: 'les noix de coco', english: 'coconut'},
    {emoji: '🥝', french: 'le kiwi', plural: 'les kiwis', english: 'kiwi'},
    {emoji: '🍅', french: 'la tomate', plural: 'les tomates', english: 'tomato'},
    {emoji: '🍆', french: 'l\'aubergine', plural: 'les aubergines', english: 'eggplant'},
    {emoji: '🥑', french: 'l\'avocat', plural: 'les avocats', english: 'avocado'},
    {emoji: '🥦', french: 'le brocoli', plural: 'les brocolis', english: 'broccoli'},
    {emoji: '🥬', french: 'la laitue', plural: 'les laitues', english: 'lettuce'},
    {emoji: '🥒', french: 'le concombre', plural: 'les concombres', english: 'cucumber'},
    {emoji: '🌶️', french: 'le piment', plural: 'les piments', english: 'chili'},
    {emoji: '🌽', french: 'le maïs', plural: 'les maïs', english: 'corn'},
    {emoji: '🥕', french: 'la carotte', plural: 'les carottes', english: 'carrot'},
    {emoji: '🧄', french: 'l\'ail', plural: 'les ails', english: 'garlic'},
    {emoji: '🧅', french: 'l\'oignon', plural: 'les oignons', english: 'onion'},
    {emoji: '🥔', french: 'la pomme de terre', plural: 'les pommes de terre', english: 'potato'},
    {emoji: '🍠', french: 'la patate douce', plural: 'les patates douces', english: 'sweet potato'},
    {emoji: '🥐', french: 'le croissant', plural: 'les croissants', english: 'croissant'},
    {emoji: '🥯', french: 'le bagel', plural: 'les bagels', english: 'bagel'},
    {emoji: '🍞', french: 'le pain', plural: 'les pains', english: 'bread'},
    {emoji: '🥖', french: 'la baguette', plural: 'les baguettes', english: 'baguette'},
    {emoji: '🥨', french: 'le bretzel', plural: 'les bretzels', english: 'pretzel'},
    {emoji: '🧀', french: 'le fromage', plural: 'les fromages', english: 'cheese'},
    {emoji: '🥚', french: 'l\'œuf', plural: 'les œufs', english: 'egg'},
    {emoji: '🍳', french: 'l\'omelette', plural: 'les omelettes', english: 'omelette'},
    {emoji: '🧈', french: 'le beurre', plural: 'les beurres', english: 'butter'},
    {emoji: '🥞', french: 'la crêpe', plural: 'les crêpes', english: 'pancake'},
    {emoji: '🧇', french: 'la gaufre', plural: 'les gaufres', english: 'waffle'},
    {emoji: '🥓', french: 'le bacon', plural: 'les bacons', english: 'bacon'},
    {emoji: '🥩', french: 'le steak', plural: 'les steaks', english: 'steak'},
    {emoji: '🍗', french: 'le poulet', plural: 'les poulets', english: 'chicken'},
    {emoji: '🍖', french: 'le côtelette', plural: 'les côtelettes', english: 'ribs'},
    {emoji: '🦴', french: 'l\'os', plural: 'les os', english: 'bone'},
    {emoji: '🌭', french: 'le hot-dog', plural: 'les hot-dogs', english: 'hot dog'},
    {emoji: '🍔', french: 'le hamburger', plural: 'les hamburgers', english: 'hamburger'},
    {emoji: '🍟', french: 'les frites', plural: 'les frites', english: 'french fries'},
    {emoji: '🍕', french: 'la pizza', plural: 'les pizzas', english: 'pizza'},
    {emoji: '🥪', french: 'le sandwich', plural: 'les sandwiches', english: 'sandwich'},
    {emoji: '🌮', french: 'le taco', plural: 'les tacos', english: 'taco'},
    {emoji: '🌯', french: 'le burrito', plural: 'les burritos', english: 'burrito'},
    {emoji: '🥙', french: 'le falafel', plural: 'les falafels', english: 'falafel'},
    {emoji: '🧆', french: 'la boulette de viande', plural: 'les boulettes de viande', english: 'meatball'},
    {emoji: '🥘', french: 'la paella', plural: 'les paellas', english: 'paella'},
    {emoji: '🍲', french: 'le pot-au-feu', plural: 'les pots-au-feu', english: 'stew'},
    {emoji: '🥣', french: 'le bol', plural: 'les bols', english: 'bowl'},
    {emoji: '🥗', french: 'la salade', plural: 'les salades', english: 'salad'},
    {emoji: '🍿', french: 'le popcorn', plural: 'les popcorns', english: 'popcorn'},
    {emoji: '🧂', french: 'le sel', plural: 'les sels', english: 'salt'},
    {emoji: '🥫', french: 'la conserve', plural: 'les conserves', english: 'canned food'},
    {emoji: '🍱', french: 'le bento', plural: 'les bentos', english: 'bento box'},
    {emoji: '🍘', french: 'le cracker de riz', plural: 'les crackers de riz', english: 'rice cracker'},
    {emoji: '🍙', french: 'l\'onigiri', plural: 'les onigiris', english: 'onigiri'},
    {emoji: '🍚', french: 'le riz', plural: 'les riz', english: 'rice'},
    {emoji: '🍛', french: 'le curry', plural: 'les curries', english: 'curry'},
    {emoji: '🍜', french: 'les nouilles', plural: 'les nouilles', english: 'noodles'},
    {emoji: '🍝', french: 'les spaghettis', plural: 'les spaghettis', english: 'spaghetti'},
    {emoji: '🍠', french: 'la patate douce', plural: 'les patates douces', english: 'sweet potato'},
    {emoji: '🍣', french: 'le sushi', plural: 'les sushis', english: 'sushi'},
    {emoji: '🍤', french: 'la crevette', plural: 'les crevettes', english: 'shrimp'},
    {emoji: '🍥', french: 'le narutomaki', plural: 'les narutomakis', english: 'fish cake'},
    {emoji: '🥮', french: 'le gâteau de lune', plural: 'les gâteaux de lune', english: 'moon cake'},
    {emoji: '🍡', french: 'le dango', plural: 'les dangos', english: 'dango'},
    {emoji: '🥟', french: 'le dumpling', plural: 'les dumplings', english: 'dumpling'},
    {emoji: '🥠', french: 'le biscuit de fortune', plural: 'les biscuits de fortune', english: 'fortune cookie'},
    {emoji: '🥡', french: 'la boîte à emporter', plural: 'les boîtes à emporter', english: 'takeout box'},
    {emoji: '🦪', french: 'l\'huître', plural: 'les huîtres', english: 'oyster'},
    {emoji: '🍦', french: 'la glace', plural: 'les glaces', english: 'ice cream'},
    {emoji: '🍧', french: 'le granité', plural: 'les granités', english: 'shaved ice'},
    {emoji: '🍨', french: 'la coupe de glace', plural: 'les coupes de glace', english: 'ice cream sundae'},
    {emoji: '🍩', french: 'le donut', plural: 'les donuts', english: 'donut'},
    {emoji: '🍪', french: 'le biscuit', plural: 'les biscuits', english: 'cookie'},
    {emoji: '🎂', french: 'le gâteau d\'anniversaire', plural: 'les gâteaux d\'anniversaire', english: 'birthday cake'},
    {emoji: '🍰', french: 'le gâteau', plural: 'les gâteaux', english: 'cake'},
    {emoji: '🧁', french: 'le cupcake', plural: 'les cupcakes', english: 'cupcake'},
    {emoji: '🥧', french: 'la tarte', plural: 'les tartes', english: 'pie'},
    {emoji: '🍫', french: 'le chocolat', plural: 'les chocolats', english: 'chocolate'},
    {emoji: '🍬', french: 'le bonbon', plural: 'les bonbons', english: 'candy'},
    {emoji: '🍭', french: 'la sucette', plural: 'les sucettes', english: 'lollipop'},
    {emoji: '🍮', french: 'le flan', plural: 'les flans', english: 'custard'},
    {emoji: '🍯', french: 'le miel', plural: 'les miels', english: 'honey'},
    {emoji: '🍼', french: 'le biberon', plural: 'les biberons', english: 'baby bottle'},
    {emoji: '🥛', french: 'le lait', plural: 'les laits', english: 'milk'},
    {emoji: '☕', french: 'le café', plural: 'les cafés', english: 'coffee'},
    {emoji: '🍵', french: 'le thé', plural: 'les thés', english: 'tea'},
    {emoji: '🍶', french: 'le sake', plural: 'les sakes', english: 'sake'},
    {emoji: '🍾', french: 'le champagne', plural: 'les champagnes', english: 'champagne'},
    {emoji: '🍷', french: 'le vin', plural: 'les vins', english: 'wine'},
    {emoji: '🍸', french: 'le cocktail', plural: 'les cocktails', english: 'cocktail'},
    {emoji: '🍹', french: 'le cocktail tropical', plural: 'les cocktails tropicaux', english: 'tropical drink'},
    {emoji: '🍺', french: 'la bière', plural: 'les bières', english: 'beer'},
    {emoji: '🍻', french: 'les chopes de bière', plural: 'les chopes de bière', english: 'clinking beer mugs'},
    {emoji: '🥂', french: 'les flûtes de champagne', plural: 'les flûtes de champagne', english: 'clinking glasses'},
    {emoji: '🥃', french: 'le whisky', plural: 'les whiskys', english: 'tumbler glass'},
    {emoji: '🥤', french: 'le soda', plural: 'les sodas', english: 'cup with straw'},
    {emoji: '🧃', french: 'le jus de fruit', plural: 'les jus de fruit', english: 'beverage box'},
    {emoji: '🧉', french: 'le maté', plural: 'les matés', english: 'mate'},
    {emoji: '🧊', french: 'le glaçon', plural: 'les glaçons', english: 'ice cube'},
    {emoji: '🥢', french: 'les baguettes', plural: 'les baguettes', english: 'chopsticks'},
    {emoji: '🍴', french: 'la fourchette et le couteau', plural: 'les fourchettes et les couteaux', english: 'fork and knife'},
    {emoji: '🥄', french: 'la cuillère', plural: 'les cuillères', english: 'spoon'},
    {emoji: '🔪', french: 'le couteau de cuisine', plural: 'les couteaux de cuisine', english: 'kitchen knife'},
    {emoji: '🍽️', french: 'le dîner', plural: 'les dîners', english: 'dinner'},
    {emoji: '🥣', french: 'le bol', plural: 'les bols', english: 'bowl'},
    {emoji: '🥡', french: 'le à emporter', plural: 'les à emporter', english: 'takeaway'},
    {emoji: '🥢', french: 'les baguettes', plural: 'les baguettes', english: 'chopsticks'},
    {emoji: '🧂', french: 'la salière', plural: 'les salières', english: 'salt shaker'}
  

    // Add more flashcards as needed
];