export const householdFlashcards = [
    
{emoji: '💌', french: 'Lettre d\'amour', plural: 'Lettres d\'amour', english: 'Love Letter'},
{emoji: '🕳', french: 'Trou', plural: 'Trous', english: 'Hole'},
{emoji: '💣', french: 'Bombe', plural: 'Bombes', english: 'Bomb'},
{emoji: '🛀', french: 'Bain', plural: 'Bains', english: 'Person Taking Bath'},
{emoji: '🛌', french: 'Lit', plural: 'Lits', english: 'Person in Bed'},
{emoji: '🔪', french: 'Couteau', plural: 'Couteaux', english: 'Kitchen Knife'},
{emoji: '🏺', french: 'Amphore', plural: 'Amphores', english: 'Amphora'},
{emoji: '🗺', french: 'Carte du monde', plural: 'Cartes du monde', english: 'World Map'},
{emoji: '🧭', french: 'Boussole', plural: 'Boussoles', english: 'Compass'},
{emoji: '🧱', french: 'Brique', plural: 'Briques', english: 'Brick'},
{emoji: '💈', french: 'Poteau de barbier', plural: 'Poteaux de barbier', english: 'Barber Pole'},
{emoji: '🦽', french: 'Fauteuil roulant manuel', plural: 'Fauteuils roulants manuels', english: 'Manual Wheelchair'},
{emoji: '🛢', french: 'Baril d\'huile', plural: 'Barils d\'huile', english: 'Oil Drum'},
{emoji: '🛎', french: 'Cloche de réception', plural: 'Cloches de réception', english: 'Bellhop Bell'},
{emoji: '🧳', french: 'Valise', plural: 'Valises', english: 'Luggage'},
{emoji: '⌛ ', french: 'Sablier', plural: 'Sabliers', english: 'Hourglass Done'},
{emoji: '⏳ ', french: 'Sablier avec sable coulant', plural: 'Sabliers avec sable coulant', english: 'Hourglass Not Done'},
{emoji: '⌚ ', french: 'Montre', plural: 'Montres', english: 'Watch'},
{emoji: '⏰ ', french: 'Réveil', plural: 'Réveils', english: 'Alarm Clock'},
{emoji: '⏱', french: 'Chronomètre', plural: 'Chronomètres', english: 'Stopwatch'},
{emoji: '⏲', french: 'Minuteur de cuisine', plural: 'Minuteries de cuisine', english: 'Timer Clock'},
{emoji: '🕰', french: 'Horloge', plural: 'Horloges', english: 'Mantelpiece Clock'},
{emoji: '🌡', french: 'Thermomètre', plural: 'Thermomètres', english: 'Thermometer'},
{emoji: '⛱', french: 'Parasol sur le sol', plural: 'Parasols sur le sol', english: 'Umbrella on Ground'},
{emoji: '🧨', french: 'Pétard', plural: 'Pétards', english: 'Firecracker'},
{emoji: '🎈', french: 'Ballon', plural: 'Ballons', english: 'Balloon'},
{emoji: '🎉', french: 'Cotillon', plural: 'Cotillons', english: 'Party Popper'},
{emoji: '🎊', french: 'Confetti', plural: 'Confettis', english: 'Confetti Ball'},
{emoji: '🎎', french: 'Poupées japonaises', plural: 'Poupées japonaises', english: 'Japanese Dolls'},
{emoji: '🎏', french: 'Carpe Koinobori', plural: 'Carpes Koinobori', english: 'Carp Streamer'},
{emoji: '🎐', french: 'Cloche de vent', plural: 'Cloches de vent', english: 'Wind Chime'},
{emoji: '🧧', french: 'Enveloppe rouge', plural: 'Enveloppes rouges', english: 'Red Envelope'},
{emoji: '🎀', french: 'Noeud ruban', plural: 'Noeuds ruban', english: 'Ribbon'},
{emoji: '🎁', french: 'Cadeau emballé', plural: 'Cadeaux emballés', english: 'Wrapped Gift'},
{emoji: '🤿', french: 'Masque de plongée', plural: 'Masques de plongée', english: 'Diving Mask'},
{emoji: '🪀', french: 'Yo-yo', plural: 'Yo-yos', english: 'Yo-Yo'},
{emoji: '🪁', french: 'Cerf-volant', plural: 'Cerfs-volants', english: 'Kite'},
{emoji: '🔮', french: 'Boule de cristal', plural: 'Boules de cristal', english: 'Crystal Ball'},
{emoji: '🧿', french: 'Amulette Nazar', plural: 'Amulettes Nazar', english: 'Nazar Amulet'},
{emoji: '🕹', french: 'Manette de jeu', plural: 'Manettes de jeu', english: 'Joystick'},
{emoji: '🧸', french: 'Ours en peluche', plural: 'Ours en peluche', english: 'Teddy Bear'},
{emoji: '🖼', french: 'Cadre photo', plural: 'Cadres photo', english: 'Framed Picture'},
{emoji: '🧵', french: 'Fil', plural: 'Fils', english: 'Thread'},
{emoji: '🧶', french: 'Fil à tricoter', plural: 'Fils à tricoter', english: 'Yarn'},
{emoji: '🛍', french: 'Sacs de magasinage', plural: 'Sacs de magasinage', english: 'Shopping Bags'},
{emoji: '📿', french: 'Chapelet', plural: 'Chapelets', english: 'Prayer Beads'},
{emoji: '💎', french: 'Pierre précieuse', plural: 'Pierres précieuses', english: 'Gem Stone'},
{emoji: '📯', french: 'Cor de poste', plural: 'Cors de poste', english: 'Postal Horn'},
{emoji: '🎙', french: 'Microphone de studio', plural: 'Microphones de studio', english: 'Studio Microphone'},
{emoji: '🎚', french: 'Curseur de niveau', plural: 'Curseurs de niveau', english: 'Level Slider'},
{emoji: '🎛', french: 'Boutons de commande', plural: 'Boutons de commande', english: 'Control Knobs'},
{emoji: '📻', french: 'Radio', plural: 'Radios', english: 'Radio'},
{emoji: '🪕', french: 'Banjo', plural: 'Banjos', english: 'Banjo'},
{emoji: '📱', french: 'Téléphone portable', plural: 'Téléphones portables', english: 'Mobile Phone'},
{emoji: '☎', french: 'Téléphone', plural: 'Téléphones', english: 'Telephone'},
{emoji: '📞', french: 'Récepteur téléphonique', plural: 'Récepteurs téléphoniques', english: 'Telephone Receiver'},
{emoji: '📟', french: 'Bipeur', plural: 'Bipeurs', english: 'Pager'},
{emoji: '📠', french: 'Fax', plural: 'Fax', english: 'Fax Machine'},
{emoji: '🔋', french: 'Pile', plural: 'Piles', english: 'Battery'},
{emoji: '🔌', french: 'Prise électrique', plural: 'Prises électriques', english: 'Electric Plug'},
{emoji: '💻', french: 'Ordinateur portable', plural: 'Ordinateurs portables', english: 'Laptop'},
{emoji: '🖥', french: 'Ordinateur de bureau', plural: 'Ordinateurs de bureau', english: 'Desktop Computer'},
{emoji: '🖨', french: 'Imprimante', plural: 'Imprimantes', english: 'Printer'},
{emoji: '⌨', french: 'Clavier', plural: 'Claviers', english: 'Keyboard'},
{emoji: '🖱', french: 'Souris d\'ordinateur', plural: 'Souris d\'ordinateur', english: 'Computer Mouse'},
{emoji: '🖲', french: 'Boule de commande', plural: 'Boules de commande', english: 'Trackball'},
{emoji: '💽', french: 'Disque d\'ordinateur', plural: 'Disques d\'ordinateur', english: 'Computer Disk'},
{emoji: '💾', french: 'Disquette', plural: 'Disquettes', english: 'Floppy Disk'},
{emoji: '💿', french: 'Disque optique', plural: 'Disques optiques', english: 'Optical Disk'},
{emoji: '📀', french: 'DVD', plural: 'DVD', english: 'DVD'},
{emoji: '🧮', french: 'Abacus', plural: 'Abacus', english: 'Abacus'},
{emoji: '🎥', french: 'Caméra de cinéma', plural: 'Caméras de cinéma', english: 'Movie Camera'},
{emoji: '🎞', french: 'Cadres de film', plural: 'Cadres de film', english: 'Film Frames'},
{emoji: '📽', french: 'Projecteur de film', plural: 'Projecteurs de film', english: 'Film Projector'},
{emoji: '📺', french: 'Télévision', plural: 'Télévisions', english: 'Television'},
{emoji: '📷', french: 'Appareil photo', plural: 'Appareils photo', english: 'Camera'},
{emoji: '📸', french: 'Appareil photo avec flash', plural: 'Appareils photo avec flash', english: 'Camera with Flash'},
{emoji: '📹', french: 'Caméra vidéo', plural: 'Caméras vidéo', english: 'Video Camera'},
{emoji: '📼', french: 'Cassette vidéo', plural: 'Cassettes vidéo', english: 'Videocassette'},
{emoji: '🔍', french: 'Loupe inclinée vers la gauche', plural: 'Loupes inclinées vers la gauche', english: 'Magnifying Glass Tilted Left'},
{emoji: '🔎', french: 'Loupe inclinée vers la droite', plural: 'Loupes inclinées vers la droite', english: 'Magnifying Glass Tilted Right'},
{emoji: '🕯', french: 'Bougie', plural: 'Bougies', english: 'Candle'},
{emoji: '💡', french: 'Ampoule', plural: 'Ampoules', english: 'Light Bulb'},
{emoji: '🔦', french: 'Lampe de poche', plural: 'Lampes de poche', english: 'Flashlight'},
{emoji: '🏮', french: 'Lanterne en papier rouge', plural: 'Lanternes en papier rouge', english: 'Red Paper Lantern'},
{emoji: '🪔', french: 'Lampe Diya', plural: 'Lampes Diya', english: 'Diya Lamp'},
{emoji: '📔', french: 'Carnet avec couverture décorative', plural: 'Carnets avec couverture décorative', english: 'Notebook with Decorative Cover'},
{emoji: '📕', french: 'Livre fermé', plural: 'Livres fermés', english: 'Closed Book'},
{emoji: '📖', french: 'Livre ouvert', plural: 'Livres ouverts', english: 'Open Book'},
{emoji: '📗', french: 'Livre vert', plural: 'Livres verts', english: 'Green Book'},
{emoji: '📘', french: 'Livre bleu', plural: 'Livres bleus', english: 'Blue Book'},
{emoji: '📙', french: 'Livre orange', plural: 'Livres oranges', english: 'Orange Book'},
{emoji: '📚', french: 'Livres', plural: 'Livres', english: 'Books'},
{emoji: '📓', french: 'Carnet', plural: 'Carnets', english: 'Notebook'},
{emoji: '📒', french: 'Grand livre', plural: 'Grands livres', english: 'Ledger'},
{emoji: '📃', french: 'Page avec bordure', plural: 'Pages avec bordure', english: 'Page with Curl'},
{emoji: '📜', french: 'Rouleau', plural: 'Rouleaux', english: 'Scroll'},
{emoji: '📄', french: 'Page vers le haut', plural: 'Pages vers le haut', english: 'Page Facing Up'},
{emoji: '📰', french: 'Journal', plural: 'Journaux', english: 'Newspaper'},
{emoji: '🗞', french: 'Journal roulé', plural: 'Journaux roulés', english: 'Rolled-Up Newspaper'},
{emoji: '📑', french: 'Onglets de signet', plural: 'Onglets de signet', english: 'Bookmark Tabs'},
{emoji: '🔖', french: 'Signet', plural: 'Signet', english: 'Bookmark'},
{emoji: '🏷', french: 'Étiquette', plural: 'Étiquette', english: 'Label'},
{emoji: '💰', french: 'Sac d\'argent', plural: 'Sacs d\'argent', english: 'Money Bag'},
{emoji: '💴', french: 'Billet de banque en yen', plural: 'Billets de banque en yen', english: 'Yen Banknote'},
{emoji: '💵', french: 'Billet de banque en dollar', plural: 'Billets de banque en dollar', english: 'Dollar Banknote'},
{emoji: '💶', french: 'Billet de banque en euro', plural: 'Billets de banque en euro', english: 'Euro Banknote'},
{emoji: '💷', french: 'Billet de banque en livre sterling', plural: 'Billets de banque en livre sterling', english: 'Pound Banknote'},
{emoji: '💸', french: 'Argent avec des ailes', plural: 'Argent avec des ailes', english: 'Money with Wings'},
{emoji: '💳', french: 'Carte de crédit', plural: 'Cartes de crédit', english: 'Credit Card'},
{emoji: '🧾', french: 'Reçu', plural: 'Reçus', english: 'Receipt'},
{emoji: '✉', french: 'Enveloppe', plural: 'Enveloppes', english: 'Envelope'},
{emoji: '📧', french: 'Courriel', plural: 'Courriels', english: 'E-Mail'},
{emoji: '📨', french: 'Enveloppe entrante', plural: 'Enveloppes entrantes', english: 'Incoming Envelope'},
{emoji: '📩', french: 'Enveloppe avec flèche', plural: 'Enveloppes avec flèche', english: 'Envelope with Arrow'},
{emoji: '📤', french: 'Boîte d\'envoi', plural: 'Boîtes d\'envoi', english: 'Outbox Tray'},
{emoji: '📥', french: 'Boîte de réception', plural: 'Boîtes de réception', english: 'Inbox Tray'},
{emoji: '📦', french: 'Paquet', plural: 'Paquets', english: 'Package'},
{emoji: '📭', french: 'Boîte aux lettres', plural: 'Boîtes aux lettres', english: 'Mailbox'},
{emoji: '📮', french: 'Boîte aux lettres', plural: 'Boîtes aux lettres', english: 'Postbox'},
{emoji: '🗳', french: 'Urne avec bulletin de vote', plural: 'Urnes avec bulletins de vote', english: 'Ballot Box with Ballot'},
{emoji: '✏', french: 'Crayon', plural: 'Crayons', english: 'Pencil'},
{emoji: '✒', french: 'Plume noire', plural: 'Plumes noires', english: 'Black Nib'},
{emoji: '🖋', french: 'Stylo à encre', plural: 'Stylos à encre', english: 'Fountain Pen'},
{emoji: '🖊', french: 'Stylo', plural: 'Stylos', english: 'Pen'},
{emoji: '🖌', french: 'Pinceau', plural: 'Pinceaux', english: 'Paintbrush'},
{emoji: '🖍', french: 'Crayon', plural: 'Crayons', english: 'Crayon'},
{emoji: '📝', french: 'Mémo', plural: 'Mémos', english: 'Memo'},
{emoji: '📁', french: 'Chemise de classement', plural: 'Chemises de classement', english: 'File Folder'},
{emoji: '📂', french: 'Chemise de classement ouverte', plural: 'Chemises de classement ouvertes', english: 'Open File Folder'},
{emoji: '🗂', french: 'Séparateurs d\'index de carte', plural: 'Séparateurs d\'index de cartes', english: 'Card Index Dividers'},
{emoji: '📅', french: 'Calendrier', plural: 'Calendriers', english: 'Calendar'},
{emoji: '📆', french: 'Calendrier à détacher', plural: 'Calendriers à détacher', english: 'Tear-Off Calendar'},
{emoji: '🗒', french: 'Bloc-notes à spirale', plural: 'Bloc-notes à spirale', english: 'Spiral Notepad'},
{emoji: '🗓', french: 'Calendrier à spirale', plural: 'Calendriers à spirale', english: 'Spiral Calendar'},
{emoji: '📇', french: 'Index de carte', plural: 'Index de cartes', english: 'Card Index'},
{emoji: '📈', french: 'Graphique en augmentation', plural: 'Graphiques en augmentation', english: 'Chart Increasing'},
{emoji: '📉', french: 'Graphique en diminution', plural: 'Graphiques en diminution', english: 'Chart Decreasing'},
{emoji: '📊', french: 'Diagramme à barres', plural: 'Diagrammes à barres', english: 'Bar Chart'},
{emoji: '📋', french: 'Presse-papiers', plural: 'Presse-papiers', english: 'Clipboard'},
{emoji: '📌', french: 'Punaise', plural: 'Punaises', english: 'Pushpin'},
{emoji: '📍', french: 'Punaise ronde', plural: 'Punaises rondes', english: 'Round Pushpin'},
{emoji: '📎', french: 'Trombone', plural: 'Trombones', english: 'Paperclip'},
{emoji: '🖇', french: 'Trombones reliés', plural: 'Trombones reliés', english: 'Linked Paperclips'},
{emoji: '📏', french: 'Règle droite', plural: 'Règles droites', english: 'Straight Ruler'},
{emoji: '📐', french: 'Règle triangulaire', plural: 'Règles triangulaires', english: 'Triangular Ruler'},
{emoji: '✂', french: 'Ciseaux', plural: 'Ciseaux', english: 'Scissors'},
{emoji: '🗃', french: 'Boîte de fiches', plural: 'Boîtes de fiches', english: 'Card File Box'},
{emoji: '🗄', french: 'Classeur', plural: 'Classeurs', english: 'File Cabinet'},
{emoji: '🗑', french: 'Corbeille à papier', plural: 'Corbeilles à papier', english: 'Wastebasket'},
{emoji: '🔒', french: 'Verrouillé', plural: 'Verrouillés', english: 'Locked'},
{emoji: '🔓', french: 'Déverrouillé', plural: 'Déverrouillés', english: 'Unlocked'},
{emoji: '🔐', french: 'Verrouillé avec une clé', plural: 'Verrouillés avec une clé', english: 'Locked with Key'},
{emoji: '🔑', french: 'Clé', plural: 'Clés', english: 'Key'},
{emoji: '🗝', french: 'Ancienne clé', plural: 'Anciennes clés', english: 'Old Key'},
{emoji: '🔨', french: 'Marteau', plural: 'Marteaux', english: 'Hammer'},
{emoji: '🪓', french: 'Hache', plural: 'Haches', english: 'Axe'},
{emoji: '⛏', french: 'Pic', plural: 'Pics', english: 'Pick'},
{emoji: '⚒', french: 'Marteau et pioche', plural: 'Marteaux et pioches', english: 'Hammer and Pick'},
{emoji: '🛠', french: 'Marteau et clé', plural: 'Marteaux et clés', english: 'Hammer and Wrench'},
{emoji: '🗡', french: 'Dague', plural: 'Dagues', english: 'Dagger'},
{emoji: '⚔', french: 'Épées croisées', plural: 'Épées croisées', english: 'Crossed Swords'},
{emoji: '🔫', french: 'Pistolet à eau', plural: 'Pistolets à eau', english: 'Water Pistol'},
{emoji: '🛡', french: 'Bouclier', plural: 'Boucliers', english: 'Shield'},
{emoji: '🔧', french: 'Clé à molette', plural: 'Clés à molette', english: 'Wrench'},
{emoji: '🔩', french: 'Écrou et boulon', plural: 'Écrous et boulons', english: 'Nut and Bolt'},
{emoji: '⚙', french: 'Engrenage', plural: 'Engrenages', english: 'Gear'},
{emoji: '🗜', french: 'Pince', plural: 'Pinces', english: 'Clamp'},
{emoji: '⚖', french: 'Balance', plural: 'Balances', english: 'Balance Scale'},
{emoji: '🦯', french: 'Canne blanche', plural: 'Canes blanches', english: 'White Cane'},
{emoji: '🔗', french: 'Lien', plural: 'Liens', english: 'Link'},
{emoji: '⛓', french: 'Chaînes', plural: 'Chaînes', english: 'Chains'},
{emoji: '🧰', french: 'Boîte à outils', plural: 'Boîtes à outils', english: 'Toolbox'},
{emoji: '🧲', french: 'Aimant', plural: 'Aimants', english: 'Magnet'},
{emoji: '⚗', french: 'Alambic', plural: 'Alambics', english: 'Alembic'},
{emoji: '🧪', french: 'Tube à essai', plural: 'Tubes à essai', english: 'Test Tube'},
{emoji: '🧫', french: 'Boîte de Pétri', plural: 'Boîtes de Pétri', english: 'Petri Dish'},
{emoji: '🧬', french: 'ADN', plural: 'ADN', english: 'DNA'},
{emoji: '🔬', french: 'Microscope', plural: 'Microscopes', english: 'Microscope'},
{emoji: '🔭', french: 'Télescope', plural: 'Télescopes', english: 'Telescope'},
{emoji: '📡', french: 'Antenne satellite', plural: 'Antennes satellites', english: 'Satellite Antenna'},
{emoji: '💉', french: 'Seringue', plural: 'Seringues', english: 'Syringe'},
{emoji: '🩸', french: 'Goutte de sang', plural: 'Gouttes de sang', english: 'Drop of Blood'},
{emoji: '💊', french: 'Pilule', plural: 'Pilules', english: 'Pill'},
{emoji: '🩹', french: 'Pansement adhésif', plural: 'Pansements adhésifs', english: 'Adhesive Bandage'},
{emoji: '🩺', french: 'Stéthoscope', plural: 'Stéthoscopes', english: 'Stethoscope'},
{emoji: '🚪', french: 'Porte', plural: 'Portes', english: 'Door'},
{emoji: '🛏', french: 'Lit', plural: 'Lits', english: 'Bed'},
{emoji: '🪑', french: 'Chaise', plural: 'Chaises', english: 'Chair'},
{emoji: '🚽', french: 'Toilette', plural: 'Toilettes', english: 'Toilet'},
{emoji: '🚿', french: 'Douche', plural: 'Douches', english: 'Shower'},
{emoji: '🛁', french: 'Baignoire', plural: 'Baignoires', english: 'Bathtub'},
{emoji: '🪒', french: 'Rasoir', plural: 'Rasoirs', english: 'Razor'},
{emoji: '🧴', french: 'Flacon de lotion', plural: 'Flacons de lotion', english: 'Lotion Bottle'},
{emoji: '🧷', french: 'Épingle de sûreté', plural: 'Épingles de sûreté', english: 'Safety Pin'},
{emoji: '🧹', french: 'Balai', plural: 'Balais', english: 'Broom'},
{emoji: '🧺', french: 'Panier', plural: 'Paniers', english: 'Basket'},
{emoji: '🧻', french: 'Rouleau de papier', plural: 'Rouleaux de papier', english: 'Roll of Paper'},
{emoji: '🧼', french: 'Savon', plural: 'Savons', english: 'Soap'},
{emoji: '🧽', french: 'Éponge', plural: 'Éponges', english: 'Sponge'},
{emoji: '🧯', french: 'Extincteur', plural: 'Extincteurs', english: 'Fire Extinguisher'},
{emoji: '🛒', french: 'Chariot de magasinage', plural: 'Chariots de magasinage', english: 'Shopping Cart'},
{emoji: '🚬', french: 'Cigarette', plural: 'Cigarettes', english: 'Cigarette'},
{emoji: '⚰', french: 'Cercueil', plural: 'Cercueils', english: 'Coffin'},
{emoji: '⚱', french: 'Urne funéraire', plural: 'Urnes funéraires', english: 'Funeral Urn'},
{emoji: '🗿', french: 'Moai', plural: 'Moais', english: 'Moai'},
{emoji: '🚰', french: 'Eau potable', plural: 'Eau potable', english: 'Potable Water'},
    
]